apiVersion: v1
kind: Service
metadata:
  name: eatnow-elasticsearch
spec:
  selector:
    app: eatnow-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eatnow-elasticsearch
spec:
  serviceName: eatnow-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: eatnow-elasticsearch
  template:
    metadata:
      labels:
        app: eatnow-elasticsearch
    spec:
      containers:
        - name: eatnow-elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: init-db
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: "single-node"
      volumes:
        - name: init-db
          hostPath:
            path: /init-db/search/persist
            type: Directory