apiVersion: v1
kind: Service
metadata:
  name: eatnow-swagger
spec:
  selector:
    app: eatnow-swagger
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatnow-swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eatnow-swagger
  template:
    metadata:
      labels:
        app: eatnow-swagger
    spec:
      containers:
        - name: eatnow-swagger
          image: ebinphilip/eatnow-swagger
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eatnow-config-map
            - configMapRef:
                name: eatnow-api-host
          imagePullPolicy: Always
---
